// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHhkAUrqi_0zzpUmB8x3D4y21AysUU7kI',
    appId: '1:122153449474:web:843a7b1df5ffe2438b0f1b',
    messagingSenderId: '122153449474',
    projectId: 'finans-984fe',
    authDomain: 'finans-984fe.firebaseapp.com',
    storageBucket: 'finans-984fe.appspot.com',
    measurementId: 'G-BW79Y1Q1XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFKchKtztmqhgFMhhme4brfUHpuF_oMY',
    appId: '1:122153449474:android:dd6601f86a09b84b8b0f1b',
    messagingSenderId: '122153449474',
    projectId: 'finans-984fe',
    storageBucket: 'finans-984fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1LRDjIqZCCkVBU27AYyWe0KbB0LhAqQ',
    appId: '1:122153449474:ios:9a3d83fa49e81dc98b0f1b',
    messagingSenderId: '122153449474',
    projectId: 'finans-984fe',
    storageBucket: 'finans-984fe.appspot.com',
    iosBundleId: 'com.sadeceis.finans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1LRDjIqZCCkVBU27AYyWe0KbB0LhAqQ',
    appId: '1:122153449474:ios:9a3d83fa49e81dc98b0f1b',
    messagingSenderId: '122153449474',
    projectId: 'finans-984fe',
    storageBucket: 'finans-984fe.appspot.com',
    iosBundleId: 'com.sadeceis.finans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHhkAUrqi_0zzpUmB8x3D4y21AysUU7kI',
    appId: '1:122153449474:web:f70d742a1835e4dd8b0f1b',
    messagingSenderId: '122153449474',
    projectId: 'finans-984fe',
    authDomain: 'finans-984fe.firebaseapp.com',
    storageBucket: 'finans-984fe.appspot.com',
    measurementId: 'G-CW1K1PNCWR',
  );
}
